version: '3'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    user: clickhouse
    ports:
      - "9000:9000"
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
    command: ["clickhouse-server", "--config-file=/etc/clickhouse-server/config.xml"]

  superset:
    image: apache/superset:latest
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_LOAD_EXAMPLES=yes
      - PYTHONPATH=/app/superset:$PYTHONPATH
    volumes:
      - ./superset_config.py:/app/superset/superset_config.py
    command: ["superset", "run", "-h", "0.0.0.0", "-p", "8088"]
volumes:
  clickhouse-data:

