version: '3'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    user: clickhouse
    ports:
      - "9000:9000"
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
    command: ["clickhouse-server", "--config-file=/etc/clickhouse-server/config.xml"]

volumes:
  clickhouse-data:
