version: '3.7'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    user: clickhouse
    mem_limit: 1024m
    mem_reservation: 512m
    environment:
      - CLICKHOUSE_DB=${BOOKCOURT_DB}
      - CLICKHOUSE_USER=${BOOKCOURT_USER}
      - CLICKHOUSE_PASSWORD=${BOOKCOURT_PASSWORD}
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
    command: ["clickhouse-server", "--config-file=/etc/clickhouse-server/config.xml"]
    networks:
      - gms-network
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${BOOKCOURT_PASSWORD} 
    mem_limit: 512m
    mem_reservation: 128m
    ports:
      - "6379:6379"
    networks:
      - gms-network

  #gms-container:
  #  image: gms-container
  #  mem_limit: 128m
  #  mem_reservation: 32m
  #  environment:
  #    - BOOKCOURT_DB=${BOOKCOURT_DB}
  #    - BOOKCOURT_USER=${BOOKCOURT_USER}
  #    - BOOKCOURT_PASSWORD=${BOOKCOURT_PASSWORD}
  #  ports:
  #    - "5078:5078"
  #  depends_on:
  #    - clickhouse
  #  networks:
  #    - gms-network

  #redis_insight:
  #  image: redislabs/redisinsight:latest
  #  container_name: redis_insight
  #  ports:
  #    - "8001:8001"
  #  networks:
  #    - gms-network

  #superset:
  #  image: apache/superset:latest
  #  ports:
  #    - "8088:8088"
  #  environment:
  #    - SUPERSET_LOAD_EXAMPLES=yes
  #    - PYTHONPATH=/app/superset:$PYTHONPATH
  #    - SUPERSET__SQLALCHEMY_DATABASE_URI=clickhouse://default:@clickhouse:9000
  #  volumes:
  #    - ./superset_config.py:/app/superset/superset_config.py
  #  command: ["superset", "run", "-h", "0.0.0.0", "-p", "8088"]
volumes:
  clickhouse-data:

networks:
  gms-network:
    driver: bridge


